name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # Met à jour tous les jours à minuit
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Update README with private stats
      env:
        GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
      run: |
        curl -o top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs?username=Heriiniiaina&show_icons=true&locale=en&layout=compact&count_private=true&include_all_commits=true&token=${GH_STATS_TOKEN}"
